// apps/example-invoice-react/src/App.tsx
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { AuthProvider, useSession } from "@sometic/react/auth";
import { Button } from "@sometic/react/button";
import { DataTable } from "@sometic/react/data";
import { Field } from "@sometic/react/field";
import { Form, useForm, useFormField } from "@sometic/react/form";
import { Input } from "@sometic/react/input";
import { QueryClientProvider, useMutation, useQuery } from "@sometic/react/query";
import { Select, Switch } from "@sometic/react/selection";
import { createFieldIds } from "@sometic/dom/field";
import { email, required } from "@sometic/validation";
import {
    emptyInvoiceFormValues,
    INVOICE_DESK_PASSWORD,
    INVOICE_DESK_USERS,
    INVOICE_NOTES_FLAG,
    invoiceAmountValidators,
    invoiceCustomerValidators,
    invoiceStatusValidators,
    invoiceToFormValues,
    parseInvoiceStatus,
    type Invoice,
    type InvoiceDeskRuntime,
    type InvoiceFormValues,
} from "@sometic/example-invoice-kit";
import {
    buttonPrimaryClassName,
    buttonQuietClassName,
    buttonSecondaryClassName,
    fieldClasses,
    formatInvoiceAmount,
    inputClassName,
    invoiceStatusBadgeClass,
    invoiceStatusOptions,
    selectClassName,
    switchClassName,
} from "./ui.js";

const emptyInvoiceRows: Invoice[] = [];

function toRecordForm(controller: {
    register: (name: string) => void;
}): NonNullable<Parameters<typeof useFormField>[2]> {
    return controller as NonNullable<Parameters<typeof useFormField>[2]>;
}

export function App(props: { runtime: InvoiceDeskRuntime }) {
    return (
        <AuthProvider auth={props.runtime.auth}>
            <QueryClientProvider client={props.runtime.app.query}>
                <Shell runtime={props.runtime} />
            </QueryClientProvider>
        </AuthProvider>
    );
}

function Shell(props: { runtime: InvoiceDeskRuntime }) {
    const session = useSession(props.runtime.auth);
    if (session.status !== "authenticated") {
        return <Login runtime={props.runtime} />;
    }
    return <Desk runtime={props.runtime} />;
}

function Login(props: { runtime: InvoiceDeskRuntime }) {
    const form = useForm({
        defaultValues: { email: "", password: "" },
    });
    const emailField = useFormField(
        "email",
        { validators: [required("Email is required"), email()] },
        toRecordForm(form),
    );
    const passwordField = useFormField(
        "password",
        { validators: [required("Password is required")] },
        toRecordForm(form),
    );
    const emailIds = useMemo(() => createFieldIds("email"), []);
    const passwordIds = useMemo(() => createFieldIds("password"), []);
    const [error, setError] = useState("");

    return (
        <main className="flex min-h-screen items-center justify-center px-4 py-10">
            <div className="w-full max-w-md">
                <p className="mb-3 inline-flex rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold tracking-wide text-indigo-700">
                    React · Tailwind CSS
                </p>
                <h1 className="text-3xl font-semibold tracking-tight text-slate-900">
                    Invoice Desk
                </h1>
                <p className="mt-2 text-sm leading-6 text-slate-600">
                    Same Sometic engines as Vue and Vanilla. This app styles unstyled Field, Input,
                    Button, Select, and DataTable slots with Tailwind utilities.
                </p>
                <div className="mt-6 grid gap-2 sm:grid-cols-2">
                    {INVOICE_DESK_USERS.map((account) => (
                        <button
                            key={account.email}
                            type="button"
                            className="rounded-xl border border-indigo-100 bg-white px-3 py-3 text-left shadow-sm transition hover:border-indigo-300 hover:shadow"
                            onClick={() => {
                                emailField.setValue(account.email);
                                passwordField.setValue(INVOICE_DESK_PASSWORD);
                            }}
                        >
                            <span className="block text-sm font-semibold text-slate-900">
                                {account.user.displayName}
                            </span>
                            <span className="mt-0.5 block truncate text-xs text-slate-500">
                                {account.email}
                            </span>
                        </button>
                    ))}
                </div>
                <p className="mt-2 text-xs text-slate-500">
                    Password for both accounts: {INVOICE_DESK_PASSWORD}
                </p>
                <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/70">
                    <Form
                        form={toRecordForm(form)}
                        className="flex flex-col gap-4"
                        onValid={async (values) => {
                            setError("");
                            try {
                                await props.runtime.auth.signIn({
                                    email: String(values["email"] ?? ""),
                                    password: String(values["password"] ?? ""),
                                });
                            } catch {
                                setError("Invalid email or password");
                                document.getElementById(emailIds.id)?.focus();
                            }
                        }}
                        onInvalid={() => {
                            document.getElementById(emailIds.id)?.focus();
                        }}
                    >
                        <Field
                            ids={emailIds}
                            label="Email"
                            required
                            invalid={emailField.meta.invalid}
                            error={emailField.meta.error}
                            classes={fieldClasses}
                        >
                            <Input
                                id={emailIds.id}
                                name="email"
                                type="email"
                                autoComplete="username"
                                value={String(emailField.value ?? "")}
                                onValueChange={emailField.setValue}
                                onBlur={emailField.onBlur}
                                required
                                invalid={emailField.meta.invalid}
                                classes={{ root: inputClassName }}
                            />
                        </Field>
                        <Field
                            ids={passwordIds}
                            label="Password"
                            required
                            invalid={passwordField.meta.invalid}
                            error={passwordField.meta.error}
                            classes={fieldClasses}
                        >
                            <Input
                                id={passwordIds.id}
                                name="password"
                                type="password"
                                autoComplete="current-password"
                                value={String(passwordField.value ?? "")}
                                onValueChange={passwordField.setValue}
                                onBlur={passwordField.onBlur}
                                required
                                invalid={passwordField.meta.invalid}
                                classes={{ root: inputClassName }}
                            />
                        </Field>
                        {error ? (
                            <p
                                className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700"
                                role="alert"
                            >
                                {error}
                            </p>
                        ) : null}
                        <Button type="submit" className={buttonPrimaryClassName}>
                            Sign in
                        </Button>
                    </Form>
                </div>
            </div>
        </main>
    );
}

function Desk(props: { runtime: InvoiceDeskRuntime }) {
    const session = useSession(props.runtime.auth);
    const [editingId, setEditingId] = useState<string | null>(null);
    const [notesEnabled, setNotesEnabled] = useState(() =>
        props.runtime.flags.isEnabled(INVOICE_NOTES_FLAG),
    );
    const form = useForm<InvoiceFormValues>({
        defaultValues: emptyInvoiceFormValues(),
    });
    const customer = useFormField(
        "customer",
        { validators: invoiceCustomerValidators },
        toRecordForm(form),
    );
    const amount = useFormField(
        "amount",
        { validators: invoiceAmountValidators },
        toRecordForm(form),
    );
    const status = useFormField(
        "status",
        { validators: invoiceStatusValidators },
        toRecordForm(form),
    );
    const notes = useFormField("notes", {}, toRecordForm(form));
    const customerIds = useMemo(() => createFieldIds("customer"), []);
    const amountIds = useMemo(() => createFieldIds("amount"), []);
    const statusIds = useMemo(() => createFieldIds("status"), []);
    const notesIds = useMemo(() => createFieldIds("notes"), []);

    useEffect(() => {
        return props.runtime.flags.subscribe(() => {
            setNotesEnabled(props.runtime.flags.isEnabled(INVOICE_NOTES_FLAG));
        });
    }, [props.runtime.flags]);

    useEffect(() => {
        return form.subscribe(() => {
            props.runtime.editorValues.current = form.getValues();
            void props.runtime.drafts.scheduleSave();
        });
    }, [form, props.runtime]);

    const http = props.runtime.app.http;
    const invoicesQuery = useQuery<Invoice[]>(
        useMemo(
            () => ({
                queryKey: ["invoices"],
                queryFn: async () => {
                    const response = await http.get<Invoice[]>("/invoices");
                    return response.data;
                },
            }),
            [http],
        ),
    );

    const persist = useMutation<Invoice, Error, InvoiceFormValues>(
        useMemo(
            () => ({
                mutationFn: async (values: InvoiceFormValues) => {
                    const parsedStatus = parseInvoiceStatus(values.status);
                    if (parsedStatus === null) {
                        throw new Error("Invalid status");
                    }
                    const payload = JSON.stringify({
                        customer: values.customer,
                        amount: Number(values.amount),
                        status: parsedStatus,
                        notes: values.notes,
                    });
                    const headers = { "Content-Type": "application/json" };
                    if (editingId) {
                        const response = await props.runtime.app.http.put<Invoice>(
                            `/invoices/${editingId}`,
                            payload,
                            { headers },
                        );
                        return response.data;
                    }
                    const response = await props.runtime.app.http.post<Invoice>(
                        "/invoices",
                        payload,
                        { headers },
                    );
                    return response.data;
                },
                onSuccess: async () => {
                    await props.runtime.app.query.invalidate(["invoices"]);
                    form.reset(emptyInvoiceFormValues());
                    props.runtime.editorValues.current = emptyInvoiceFormValues();
                    setEditingId(null);
                },
            }),
            [editingId, form, props.runtime],
        ),
    );

    const startNew = useCallback(() => {
        setEditingId(null);
        form.reset(emptyInvoiceFormValues());
        props.runtime.editorValues.current = emptyInvoiceFormValues();
    }, [form, props.runtime]);

    const loadInvoice = useCallback(
        (invoice: Invoice) => {
            setEditingId(invoice.id);
            const values = invoiceToFormValues(invoice);
            form.reset(values);
            props.runtime.editorValues.current = values;
        },
        [form, props.runtime],
    );

    const displayName = session.user?.displayName ?? session.user?.email ?? "Signed in";

    return (
        <main className="mx-auto min-h-screen max-w-6xl px-4 py-8">
            <header className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white px-5 py-4 shadow-sm">
                <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">
                        React · Tailwind CSS
                    </p>
                    <h1 className="text-2xl font-semibold tracking-tight text-slate-900">
                        Invoice Desk
                    </h1>
                    <p className="text-sm text-slate-500">{displayName}</p>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                    <label className="flex cursor-pointer items-center gap-2 text-sm text-slate-600">
                        <Switch
                            checked={notesEnabled}
                            className={switchClassName}
                            onCheckedChange={(checked: boolean) => {
                                props.runtime.flags.setOverride(
                                    INVOICE_NOTES_FLAG,
                                    checked ? null : { enabled: false },
                                );
                            }}
                        />
                        Show notes
                    </label>
                    <Button
                        type="button"
                        className={buttonQuietClassName}
                        onClick={() => {
                            void props.runtime.auth.signOut();
                        }}
                    >
                        Sign out
                    </Button>
                </div>
            </header>
            <div className="grid gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(20rem,0.9fr)]">
                <section
                    className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"
                    aria-labelledby="invoice-list-heading"
                >
                    <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                        <div>
                            <h2
                                id="invoice-list-heading"
                                className="text-lg font-semibold text-slate-900"
                            >
                                Invoices
                            </h2>
                            <p className="text-sm text-slate-500">Click a customer to edit.</p>
                        </div>
                        <Button
                            type="button"
                            className={buttonSecondaryClassName}
                            onClick={startNew}
                        >
                            New invoice
                        </Button>
                    </div>
                    <DataTable
                        columns={[
                            {
                                id: "number",
                                header: "Number",
                                accessor: (row: Invoice) => row.number,
                                sortable: true,
                            },
                            {
                                id: "customer",
                                header: "Customer",
                                accessor: (row: Invoice) => row.customer,
                                sortable: true,
                            },
                            {
                                id: "amount",
                                header: "Amount",
                                accessor: (row: Invoice) => row.amount,
                                sortable: true,
                            },
                            {
                                id: "status",
                                header: "Status",
                                accessor: (row: Invoice) => row.status,
                                sortable: true,
                            },
                        ]}
                        rows={invoicesQuery.data ?? emptyInvoiceRows}
                        getRowId={(row) => row.id}
                        selectable={false}
                        label="Invoices"
                        emptyLabel={invoicesQuery.isPending ? "Loading invoices" : "No invoices"}
                        className="w-full"
                        renderCell={(row, column) => {
                            if (column.id === "customer") {
                                return (
                                    <button
                                        type="button"
                                        className="font-medium text-indigo-700 underline-offset-2 hover:underline"
                                        onClick={() => {
                                            loadInvoice(row);
                                        }}
                                    >
                                        {row.customer}
                                    </button>
                                );
                            }
                            if (column.id === "amount") {
                                return formatInvoiceAmount(row.amount);
                            }
                            if (column.id === "status") {
                                return (
                                    <span className={invoiceStatusBadgeClass(row.status)}>
                                        {row.status}
                                    </span>
                                );
                            }
                            const value = column.accessor?.(row);
                            return value === undefined ? "" : String(value);
                        }}
                    />
                </section>
                <section
                    className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:sticky lg:top-6"
                    aria-labelledby="invoice-editor-heading"
                >
                    <h2
                        id="invoice-editor-heading"
                        className="mb-4 text-lg font-semibold text-slate-900"
                    >
                        {editingId ? "Edit invoice" : "New invoice"}
                    </h2>
                    <form
                        className="flex flex-col gap-4"
                        noValidate
                        onSubmit={(event: FormEvent) => {
                            event.preventDefault();
                            void form.handleSubmit({
                                onValid: async (values) => {
                                    await persist.mutate(values);
                                },
                                onInvalid: () => {
                                    document.getElementById(customerIds.id)?.focus();
                                },
                            })();
                        }}
                    >
                        <Field
                            ids={customerIds}
                            label="Customer"
                            required
                            invalid={customer.meta.invalid}
                            error={customer.meta.error}
                            classes={fieldClasses}
                        >
                            <Input
                                id={customerIds.id}
                                name="customer"
                                value={String(customer.value ?? "")}
                                onValueChange={customer.setValue}
                                onBlur={customer.onBlur}
                                required
                                invalid={customer.meta.invalid}
                                classes={{ root: inputClassName }}
                            />
                        </Field>
                        <Field
                            ids={amountIds}
                            label="Amount"
                            required
                            invalid={amount.meta.invalid}
                            error={amount.meta.error}
                            classes={fieldClasses}
                        >
                            <Input
                                id={amountIds.id}
                                name="amount"
                                inputMode="decimal"
                                value={String(amount.value ?? "")}
                                onValueChange={amount.setValue}
                                onBlur={amount.onBlur}
                                required
                                invalid={amount.meta.invalid}
                                classes={{ root: inputClassName }}
                            />
                        </Field>
                        <Field
                            ids={statusIds}
                            label="Status"
                            required
                            invalid={status.meta.invalid}
                            error={status.meta.error}
                            classes={fieldClasses}
                        >
                            <Select
                                id={statusIds.id}
                                name="status"
                                value={String(status.value ?? "draft")}
                                options={[...invoiceStatusOptions]}
                                onValueChange={(value: string | null) => {
                                    status.setValue(value ?? "draft");
                                }}
                                onBlur={status.onBlur}
                                required
                                className={selectClassName}
                            />
                        </Field>
                        {notesEnabled ? (
                            <Field ids={notesIds} label="Notes" classes={fieldClasses}>
                                <Input
                                    id={notesIds.id}
                                    name="notes"
                                    value={String(notes.value ?? "")}
                                    onValueChange={notes.setValue}
                                    classes={{ root: inputClassName }}
                                />
                            </Field>
                        ) : null}
                        {persist.isError ? (
                            <p
                                className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700"
                                role="alert"
                            >
                                Could not save the invoice.
                            </p>
                        ) : null}
                        <Button
                            type="submit"
                            disabled={persist.isPending}
                            className={buttonPrimaryClassName}
                        >
                            Save
                        </Button>
                    </form>
                </section>
            </div>
        </main>
    );
}

// apps/example-invoice-vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { createFieldIds } from "@sometic/dom/field";
import { email, required } from "@sometic/validation";
import { useAuth } from "@sometic/vue/auth";
import { Button } from "@sometic/vue/button";
import { DataTable } from "@sometic/vue/data";
import { Field } from "@sometic/vue/field";
import { useForm, useFormField } from "@sometic/vue/form";
import { Input } from "@sometic/vue/input";
import { useMutation, useQuery } from "@sometic/vue/query";
import { Select, Switch } from "@sometic/vue/selection";
import {
    emptyInvoiceFormValues,
    INVOICE_DESK_PASSWORD,
    INVOICE_DESK_USERS,
    INVOICE_NOTES_FLAG,
    invoiceAmountValidators,
    invoiceCustomerValidators,
    invoiceStatusValidators,
    invoiceToFormValues,
    parseInvoiceStatus,
    type Invoice,
    type InvoiceDeskRuntime,
    type InvoiceFormValues,
} from "@sometic/example-invoice-kit";

const props = defineProps<{ runtime: InvoiceDeskRuntime }>();
const { session } = useAuth(props.runtime.auth);

const loginError = ref("");
const loginForm = useForm({ defaultValues: { email: "", password: "" } });
const loginEmail = useFormField(loginForm.form, "email", {
    validators: [required("Email is required"), email()],
});
const loginPassword = useFormField(loginForm.form, "password", {
    validators: [required("Password is required")],
});
const loginEmailIds = createFieldIds("email");
const loginPasswordIds = createFieldIds("password");

const notesEnabled = ref(props.runtime.flags.isEnabled(INVOICE_NOTES_FLAG));
props.runtime.flags.subscribe(() => {
    notesEnabled.value = props.runtime.flags.isEnabled(INVOICE_NOTES_FLAG);
});

const editingId = ref<string | null>(null);
const editorForm = useForm<InvoiceFormValues>({
    defaultValues: emptyInvoiceFormValues(),
});
const customer = useFormField(editorForm.form, "customer", {
    validators: invoiceCustomerValidators,
});
const amount = useFormField(editorForm.form, "amount", {
    validators: invoiceAmountValidators,
});
const status = useFormField(editorForm.form, "status", {
    validators: invoiceStatusValidators,
});
const notes = useFormField(editorForm.form, "notes");
const customerIds = createFieldIds("customer");
const amountIds = createFieldIds("amount");
const statusIds = createFieldIds("status");
const notesIds = createFieldIds("notes");
const invoiceStatusOptions = [
    { value: "draft", label: "Draft" },
    { value: "sent", label: "Sent" },
    { value: "paid", label: "Paid" },
];

watch(
    () => editorForm.values.value,
    (values) => {
        props.runtime.editorValues.current = values;
        void props.runtime.drafts.scheduleSave();
    },
    { deep: true },
);

const invoicesQuery = useQuery<Invoice[]>(
    computed(() => ({
        queryKey: ["invoices"],
        enabled: session.value.status === "authenticated",
        queryFn: async () => {
            const response = await props.runtime.app.http.get<Invoice[]>("/invoices");
            return response.data;
        },
    })),
);

const persist = useMutation<Invoice, Error, InvoiceFormValues>({
    mutationFn: async (values) => {
        const parsedStatus = parseInvoiceStatus(values.status);
        if (parsedStatus === null) {
            throw new Error("Invalid status");
        }
        const payload = JSON.stringify({
            customer: values.customer,
            amount: Number(values.amount),
            status: parsedStatus,
            notes: values.notes,
        });
        const headers = { "Content-Type": "application/json" };
        if (editingId.value) {
            const response = await props.runtime.app.http.put<Invoice>(
                `/invoices/${editingId.value}`,
                payload,
                { headers },
            );
            return response.data;
        }
        const response = await props.runtime.app.http.post<Invoice>("/invoices", payload, {
            headers,
        });
        return response.data;
    },
    onSuccess: async () => {
        await props.runtime.app.query.invalidate(["invoices"]);
        editorForm.form.reset(emptyInvoiceFormValues());
        props.runtime.editorValues.current = emptyInvoiceFormValues();
        editingId.value = null;
    },
});

const displayName = computed(
    () => session.value.user?.displayName ?? session.value.user?.email ?? "Signed in",
);

const invoiceRows = computed(() => (invoicesQuery.value.data ?? []) as Record<string, unknown>[]);

const invoiceColumns = [
    {
        id: "number",
        header: "Number",
        accessor: (row: Record<string, unknown>) => row["number"],
        sortable: true,
    },
    {
        id: "customer",
        header: "Customer",
        accessor: (row: Record<string, unknown>) => row["customer"],
        sortable: true,
    },
    {
        id: "amount",
        header: "Amount",
        accessor: (row: Record<string, unknown>) =>
            new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(
                Number(row["amount"] ?? 0),
            ),
        sortable: true,
    },
    {
        id: "status",
        header: "Status",
        accessor: (row: Record<string, unknown>) => row["status"],
        sortable: true,
    },
];

function fillAccount(emailAddress: string): void {
    loginEmail.setValue(emailAddress);
    loginPassword.setValue(INVOICE_DESK_PASSWORD);
}

async function onLogin(event: Event): Promise<void> {
    event.preventDefault();
    await loginForm.form.handleSubmit({
        onValid: async (values) => {
            loginError.value = "";
            try {
                await props.runtime.auth.signIn({
                    email: String(values["email"] ?? ""),
                    password: String(values["password"] ?? ""),
                });
            } catch {
                loginError.value = "Invalid email or password";
                document.getElementById(loginEmailIds.id)?.focus();
            }
        },
        onInvalid: () => {
            document.getElementById(loginEmailIds.id)?.focus();
        },
    })();
}

async function onSave(event: Event): Promise<void> {
    event.preventDefault();
    await editorForm.form.handleSubmit({
        onValid: async (values) => {
            await persist.value.mutate(values);
        },
        onInvalid: () => {
            document.getElementById(customerIds.id)?.focus();
        },
    })();
}

function startNew(): void {
    editingId.value = null;
    editorForm.form.reset(emptyInvoiceFormValues());
    props.runtime.editorValues.current = emptyInvoiceFormValues();
}

function loadInvoice(invoice: Invoice): void {
    editingId.value = invoice.id;
    const values = invoiceToFormValues(invoice);
    editorForm.form.reset(values);
    props.runtime.editorValues.current = values;
}

function onInvoiceTableClick(event: MouseEvent): void {
    const target = event.target;
    if (!(target instanceof Element)) {
        return;
    }
    const row = target.closest("[data-row-id]");
    const id = row?.getAttribute("data-row-id");
    if (!id) {
        return;
    }
    const invoice = invoicesQuery.value.data?.find((item) => item.id === id);
    if (invoice) {
        loadInvoice(invoice);
    }
}

function invoiceRowId(row: Record<string, unknown>): string {
    return String(row["id"] ?? "");
}

function onNotesChange(checked: boolean): void {
    props.runtime.flags.setOverride(INVOICE_NOTES_FLAG, checked ? null : { enabled: false });
}
</script>

<template>
    <main
        class="ledger-shell"
        :data-surface="session.status === 'authenticated' ? 'desk' : 'login'"
    >
        <template v-if="session.status !== 'authenticated'">
            <p class="ledger-kicker">Vue · Plain CSS</p>
            <h1>Invoice Desk</h1>
            <p class="ledger-lede">
                Same Sometic engines as React and Vanilla. This app styles unstyled slots with
                hand-written CSS and
                <code>data-slot</code>
                selectors.
            </p>
            <div class="ledger-accounts">
                <button
                    v-for="account in INVOICE_DESK_USERS"
                    :key="account.email"
                    type="button"
                    class="ledger-account"
                    @click="fillAccount(account.email)"
                >
                    <strong>{{ account.user.displayName }}</strong>
                    <span>{{ account.email }}</span>
                </button>
            </div>
            <p class="ledger-hint">Password for both accounts: {{ INVOICE_DESK_PASSWORD }}</p>
            <div class="ledger-card">
                <form class="ledger-form" novalidate @submit="onLogin">
                    <Field
                        :ids="loginEmailIds"
                        label="Email"
                        required
                        :invalid="loginEmail.meta.value.invalid"
                        :error="loginEmail.meta.value.error"
                    >
                        <Input
                            :id="loginEmailIds.id"
                            name="email"
                            type="email"
                            autocomplete="username"
                            :model-value="String(loginEmail.value.value ?? '')"
                            required
                            :invalid="loginEmail.meta.value.invalid"
                            @update:model-value="loginEmail.setValue"
                            @blur="loginEmail.onBlur"
                        />
                    </Field>
                    <Field
                        :ids="loginPasswordIds"
                        label="Password"
                        required
                        :invalid="loginPassword.meta.value.invalid"
                        :error="loginPassword.meta.value.error"
                    >
                        <Input
                            :id="loginPasswordIds.id"
                            name="password"
                            type="password"
                            autocomplete="current-password"
                            :model-value="String(loginPassword.value.value ?? '')"
                            required
                            :invalid="loginPassword.meta.value.invalid"
                            @update:model-value="loginPassword.setValue"
                            @blur="loginPassword.onBlur"
                        />
                    </Field>
                    <p v-if="loginError" class="ledger-alert" role="alert">{{ loginError }}</p>
                    <Button type="submit">Sign in</Button>
                </form>
            </div>
        </template>
        <template v-else>
            <header class="ledger-header">
                <div>
                    <p class="ledger-kicker">Vue · Plain CSS</p>
                    <h1>Invoice Desk</h1>
                    <p class="ledger-lede">{{ displayName }}</p>
                </div>
                <div class="ledger-actions">
                    <label class="ledger-toggle">
                        <Switch :checked="notesEnabled" @checked-change="onNotesChange" />
                        Show notes
                    </label>
                    <Button type="button" variant="quiet" @click="props.runtime.auth.signOut()">
                        Sign out
                    </Button>
                </div>
            </header>
            <div class="ledger-grid">
                <section class="ledger-card" aria-labelledby="invoice-list-heading">
                    <div class="ledger-card-head">
                        <div>
                            <h2 id="invoice-list-heading">Invoices</h2>
                            <p class="ledger-lede">Click a row to edit.</p>
                        </div>
                        <Button type="button" variant="secondary" @click="startNew">
                            New invoice
                        </Button>
                    </div>
                    <div @click="onInvoiceTableClick">
                        <DataTable
                            :columns="invoiceColumns"
                            :rows="invoiceRows"
                            :get-row-id="invoiceRowId"
                            :selectable="false"
                            label="Invoices"
                            :empty-label="
                                invoicesQuery.isPending ? 'Loading invoices' : 'No invoices'
                            "
                        />
                    </div>
                </section>
                <section class="ledger-card ledger-editor" aria-labelledby="invoice-editor-heading">
                    <h2 id="invoice-editor-heading">
                        {{ editingId ? "Edit invoice" : "New invoice" }}
                    </h2>
                    <form class="ledger-form" novalidate @submit="onSave">
                        <Field
                            :ids="customerIds"
                            label="Customer"
                            required
                            :invalid="customer.meta.value.invalid"
                            :error="customer.meta.value.error"
                        >
                            <Input
                                :id="customerIds.id"
                                name="customer"
                                :model-value="String(customer.value.value ?? '')"
                                required
                                :invalid="customer.meta.value.invalid"
                                @update:model-value="customer.setValue"
                                @blur="customer.onBlur"
                            />
                        </Field>
                        <Field
                            :ids="amountIds"
                            label="Amount"
                            required
                            :invalid="amount.meta.value.invalid"
                            :error="amount.meta.value.error"
                        >
                            <Input
                                :id="amountIds.id"
                                name="amount"
                                inputmode="decimal"
                                :model-value="String(amount.value.value ?? '')"
                                required
                                :invalid="amount.meta.value.invalid"
                                @update:model-value="amount.setValue"
                                @blur="amount.onBlur"
                            />
                        </Field>
                        <Field
                            :ids="statusIds"
                            label="Status"
                            required
                            :invalid="status.meta.value.invalid"
                            :error="status.meta.value.error"
                        >
                            <Select
                                :id="statusIds.id"
                                name="status"
                                :model-value="String(status.value.value ?? 'draft')"
                                :options="invoiceStatusOptions"
                                required
                                @update:model-value="
                                    (value: string | null) => status.setValue(value ?? 'draft')
                                "
                                @blur="status.onBlur"
                            />
                        </Field>
                        <Field v-if="notesEnabled" :ids="notesIds" label="Notes">
                            <Input
                                :id="notesIds.id"
                                name="notes"
                                :model-value="String(notes.value.value ?? '')"
                                @update:model-value="notes.setValue"
                            />
                        </Field>
                        <p v-if="persist.isError" class="ledger-alert" role="alert">
                            Could not save the invoice.
                        </p>
                        <Button type="submit" :disabled="persist.isPending">Save</Button>
                    </form>
                </section>
            </div>
        </template>
    </main>
</template>
